- name: restart bind
  become: True
  service:
    name: named
    state: restarted
    enabled: yes

- name: restart asterisk
  become: True
  service:
    name: asterisk
    state: restarted
    enabled: yes

- name: restart homeassistant
  become: True
  service:
    name: homeassistant
    state: restarted
    enabled: yes

- name: reboot
  become: True
  reboot:
    reboot_timeout: 300
