all:
  vars:
    ansible_user: ansible_user
    ansible_python_interpreter: /usr/bin/python3
  children:
    home_servers:
      children:
        home_ep:
          hosts:
            home-ep.ladon-tiaki.ts.net:
    oci_servers:
      vars:
        ansible_ssh_common_args: -F ./ssh_config # -o ProxyCommand="cloudflared access ssh --hostname %h" -i ~/.cloudflared/%h-cf_key ~/.cloudflared/%h-cf_key-cert.pub
      children: 
        oci_arm:
          hosts:
            arm-srv.shiron.dev:
