---
- name: apt-get update
  become: True
  apt:

- name: add homeassistant user
  become: True
  user:
    name: homeassistant
    system: yes

- name: mkdir /srv/homeassistant
  become: True
  file:
    path: /srv/homeassistant
    state: directory
    owner: homeassistant
    group: homeassistant
  notify: restart homeassistant

- name: Install the dependencies
  become: True
  apt:
    name:
    - python3
    - python3-dev
    - python3-venv
    - python3-pip
    - bluez
    - libffi-dev
    - libssl-dev
    - libjpeg-dev
    - zlib1g-dev
    - autoconf
    - build-essential
    - libopenjp2-7
    - libtiff6
    - libturbojpeg0-dev
    - tzdata
    - ffmpeg
    - liblapack3
    - liblapack-dev
    - libatlas-base-dev
  notify: restart homeassistant

- name: make virtualenv
  become: True
  command: python3 -m venv /srv/homeassistant
  remote_user: homeassistant
  args:
    creates: /srv/homeassistant/bin/activate
  notify: restart homeassistant

- name: chmod -R /srv/homeassistant
  become: True
  file:
    path: /srv/homeassistant
    state: directory
    owner: homeassistant
    group: homeassistant
    mode: '0755'
    recurse: yes
  notify: restart homeassistant

- name: check pip install package
  remote_user: homeassistant
  pip:
    name:
      - wheel
      - homeassistant==2024.2.3
    virtualenv: /srv/homeassistant
  check_mode: yes
  register: pip_check

- name: mkdir /pip_tmp
  become: True
  file:
    path: /pip_tmp
    state: directory
    owner: homeassistant
    group: homeassistant
  when: pip_check.changed

- name: pip install
  remote_user: homeassistant
  become: True
  pip:
    name:
      - wheel
      - homeassistant==2024.2.3
    virtualenv: /srv/homeassistant
  environment: 
    TMPDIR: /pip_tmp
    TEMP: /pip_tmp
    TMP: /pip_tmp
  when: pip_check.changed
  notify: restart homeassistant

- name: remove /pip_tmp
  become: True
  file:
    path: /pip_tmp
    state: absent
  when: pip_check.changed

- name: create systemd service
  become: True
  template:
    src: homeassistant.service
    dest: /etc/systemd/system/homeassistant@homeassistant.service
  notify: restart homeassistant
