---
- name: mkdir /var/home-assistant/config
  become: true
  file:
    path: /var/home-assistant/config
    state: directory
    mode: '0777'

- name: Make compose.yml
  template:
    src: compose.yml
    dest: /var/home-assistant/compose.yml
    mode: '0644'

- name: Make configuration.yaml
  template:
    src: configuration.yaml
    dest: /var/home-assistant/config/configuration.yaml
    mode: '0644'

- name: docker compose up
  shell:
    cmd: "docker compose -f /var/home-assistant/compose.yml up -d"
    chdir: /var/home-assistant
