apiVersion: 1

datasources:
  - name: Prometheus-vm_{{ ansible_play_hosts[0] }}
    type: prometheus
    access: proxy
    url: http://{{ item }}:8428
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
