---
- name: Restart prometheus
  become: true
  ansible.builtin.service:
    name: prometheus
    state: restarted
    enabled: true

- name: Restart node-exporter
  ansible.builtin.command:
    cmd: docker compose -f /var/prometheus/compose.yml up -d
    chdir: /var/prometheus
  changed_when: true
