version: "2"
linters:
  default: all
  enable:
    - wsl_v5
  disable:
    - depguard
    - wrapcheck
    - ireturn
    - wsl
    - varnamelen
  exclusions:
    rules:
      - path: (.+)_test\.go
        linters:
          - dupl
          - exhaustruct
          - funlen
          - testpackage
          - cyclop

  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
    varnamelen:
      ignore-decls:
        - i int
      ignore-names:
        - tt
