- name: Ensure runtime directories with correct ownership
  become: true
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode | default('0755') }}"
    recurse: "{{ item.recurse | default(false) }}"
  loop:
    - {path: "/var/grafana/grafana_conf/provisioning/datasources", owner: "root", group: "root", mode: "0755"}
    - {path: "/var/grafana/grafana_storage", owner: "472", group: "0", mode: "0755", recurse: true}
    - {path: "/var/grafana/influxdb_data", owner: "1000", group: "1000", mode: "0755"}
    - {path: "/var/grafana/influxdb_config", owner: "1000", group: "1000", mode: "0755"}
    - {path: "/var/grafana/vmdata", owner: "1000", group: "1000", mode: "0755"}
  notify: Restart grafana

- name: Make compose.yml
  ansible.builtin.template:
    src: compose.yml
    dest: /var/grafana/compose.yml
    mode: "0644"
  notify: Restart grafana

- name: Make datasource.yml
  ansible.builtin.template:
    src: datasource.yml
    dest: /var/grafana/grafana_conf/provisioning/datasources/localhost_vmprom.yml
    mode: "0644"
  notify: Restart grafana

- name: Make prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml
    dest: /var/grafana/prometheus.yml
    mode: "0644"
  notify: Restart grafana

- name: Make conf
  ansible.builtin.template:
    src: "{{ item }}"
    dest: /var/grafana/grafana_conf/{{ item | basename }}
    mode: "0644"
  with_fileglob:
    - templates/conf/*
  notify: Restart grafana

