---
- name: Make grafana directory
  become: true
  ansible.builtin.file:
    path: /var/grafana
    state: directory
    mode: "0777"

- name: Make compose.yml
  ansible.builtin.template:
    src: compose.yml
    dest: /var/grafana/compose.yml
    mode: "0644"
  notify: Restart grafana
