---
- name: Apt-get update
  become: true
  ansible.builtin.apt:

- name: Mkdir /var/asterisk
  become: true
  ansible.builtin.file:
    path: /var/asterisk
    state: directory
    mode: "0777"
  register: asterisk_dir

- name: Download asterisk
  ansible.builtin.get_url:
    url: https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-20.7.0.tar.gz
    dest: /var/asterisk/asterisk.tar.gz
    mode: "0644"
  when: asterisk_dir.changed
  register: asterisk_download

- name: Extract asterisk
  ansible.builtin.unarchive:
    src: /var/asterisk/asterisk.tar.gz
    dest: /var/asterisk
    mode: "0644"
    remote_src: true
  when: asterisk_download.changed

- name: Install prereq
  become: true
  ansible.builtin.command: ./install_prereq install
  args:
    chdir: /var/asterisk/asterisk-20.7.0/contrib/scripts
  when: asterisk_download.changed

- name: Configure
  become: true
  ansible.builtin.command: ./configure --with-pjproject-bundled
  args:
    chdir: /var/asterisk/asterisk-20.7.0
  when: asterisk_download.changed

- name: Make
  become: true
  community.general.make:
    chdir: /var/asterisk/asterisk-20.7.0
  when: asterisk_download.changed

- name: Make install
  become: true
  community.general.make:
    chdir: /var/asterisk/asterisk-20.7.0
    target: install
  when: asterisk_download.changed

- name: Make samples
  become: true
  community.general.make:
    chdir: /var/asterisk/asterisk-20.7.0
    target: samples
  when: asterisk_download.changed

- name: Make config
  become: true
  community.general.make:
    chdir: /var/asterisk/asterisk-20.7.0
    target: config
  when: asterisk_download.changed

- name: Make install-logrotate
  become: true
  community.general.make:
    chdir: /var/asterisk/asterisk-20.7.0
    target: install-logrotate
  when: asterisk_download.changed

- name: Update service file
  become: true
  ansible.builtin.template:
    src: asterisk.service.j2
    dest: /lib/systemd/system/asterisk.service
    mode: "0644"
  notify: restart asterisk
  register: asterisk_service

- name: Daemon reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  changed_when:
  when: asterisk_service.changed

- name: Make pjsip.conf
  become: true
  ansible.builtin.template:
    src: pjsip.conf.j2
    dest: /etc/asterisk/pjsip.conf
    mode: "0644"
  notify: restart asterisk

- name: Make pjsip_wizard.conf
  become: true
  ansible.builtin.template:
    src: pjsip_wizard.conf.j2
    dest: /etc/asterisk/pjsip_wizard.conf
    mode: "0644"
  notify: restart asterisk

- name: Make extensions.conf
  become: true
  ansible.builtin.template:
    src: extensions.conf.j2
    dest: /etc/asterisk/extensions.conf
    mode: "0644"
  notify: restart asterisk

- name: Make cdr.conf
  become: true
  ansible.builtin.template:
    src: cdr.conf.j2
    dest: /etc/asterisk/cdr.conf
    mode: "0644"
  notify: restart asterisk

- name: Make cel.conf
  become: true
  ansible.builtin.template:
    src: cel.conf.j2
    dest: /etc/asterisk/cel.conf
    mode: "0644"
  notify: restart asterisk

- name: Make modules.conf
  become: true
  ansible.builtin.template:
    src: modules.conf.j2
    dest: /etc/asterisk/modules.conf
    mode: "0644"
  notify: restart asterisk

- name: Make logger.conf
  become: true
  ansible.builtin.template:
    src: logger.conf.j2
    dest: /etc/asterisk/logger.conf
    mode: "0644"
  notify: restart asterisk

- name: Enable Asterisk
  become: true
  ansible.builtin.service:
    name: asterisk
    enabled: true
