---
- name: Mkdir /var/asterisk
  become: true
  ansible.builtin.file:
    path: /var/asterisk
    state: directory
    mode: "0777"

- name: Download asterisk
  ansible.builtin.get_url:
    url: https://downloads.asterisk.org/pub/telephony/asterisk/asterisk-20.7.0.tar.gz
    dest: /var/asterisk/asterisk.tar.gz
    mode: "0644"

- name: Extract asterisk
  ansible.builtin.unarchive:
    src: /var/asterisk/asterisk.tar.gz
    dest: /var/asterisk
    mode: "0644"
    remote_src: true
  notify: install_asterisk
