- name: enable init_task
  become: True
  systemd:
    name: init_task
    enabled: yes
    state: started
    daemon_reload: yes
  notify: reboot

- name: reboot
  become: True
  reboot:
    reboot_timeout: 300
