apiVersion: 1

datasources:
  - name: Prometheus-vm_localhost
    type: prometheus
    access: proxy
    url: http://victoriametrics:8428
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.24.0
