---
- name: Restart asterisk
  listen: Restart_asterisk
  become: true
  ansible.builtin.service:
    name: asterisk
    state: Restarted
    enabled: true

- name: Daemon reload
  listen: daemon_reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true

- name: Install Asterisk
  ansible.builtin.import_tasks: install.yml

- name: Make config
  listen: config_asterisk
  ansible.builtin.import_tasks: config.yml
