---
- name: Mkdir /var/portainer
  become: true
  ansible.builtin.file:
    path: /var/portainer
    state: directory
    mode: "0755"

- name: Make compose.yml
  become: true
  ansible.builtin.template:
    src: compose.yml
    dest: /var/portainer/compose.yml
    mode: "0644"
  notify: Restart portainer
