// Code generated by MockGen. DO NOT EDIT.
// Source: cmt/internal/config (interfaces: SSHConfigRunner,SSHConfigResolver)
//
// Generated by this command:
//
//	mockgen -destination=mock_ssh_interfaces.go -package=config cmt/internal/config SSHConfigRunner,SSHConfigResolver
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSHConfigRunner is a mock of SSHConfigRunner interface.
type MockSSHConfigRunner struct {
	ctrl     *gomock.Controller
	recorder *MockSSHConfigRunnerMockRecorder
	isgomock struct{}
}

// MockSSHConfigRunnerMockRecorder is the mock recorder for MockSSHConfigRunner.
type MockSSHConfigRunnerMockRecorder struct {
	mock *MockSSHConfigRunner
}

// NewMockSSHConfigRunner creates a new mock instance.
func NewMockSSHConfigRunner(ctrl *gomock.Controller) *MockSSHConfigRunner {
	mock := &MockSSHConfigRunner{ctrl: ctrl}
	mock.recorder = &MockSSHConfigRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHConfigRunner) EXPECT() *MockSSHConfigRunnerMockRecorder {
	return m.recorder
}

// Output mocks base method.
func (m *MockSSHConfigRunner) Output(name string, args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{name}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Output", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Output indicates an expected call of Output.
func (mr *MockSSHConfigRunnerMockRecorder) Output(name any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{name}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockSSHConfigRunner)(nil).Output), varargs...)
}

// MockSSHConfigResolver is a mock of SSHConfigResolver interface.
type MockSSHConfigResolver struct {
	ctrl     *gomock.Controller
	recorder *MockSSHConfigResolverMockRecorder
	isgomock struct{}
}

// MockSSHConfigResolverMockRecorder is the mock recorder for MockSSHConfigResolver.
type MockSSHConfigResolverMockRecorder struct {
	mock *MockSSHConfigResolver
}

// NewMockSSHConfigResolver creates a new mock instance.
func NewMockSSHConfigResolver(ctrl *gomock.Controller) *MockSSHConfigResolver {
	mock := &MockSSHConfigResolver{ctrl: ctrl}
	mock.recorder = &MockSSHConfigResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHConfigResolver) EXPECT() *MockSSHConfigResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockSSHConfigResolver) Resolve(entry *HostEntry, sshConfigPath, hostDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", entry, sshConfigPath, hostDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockSSHConfigResolverMockRecorder) Resolve(entry, sshConfigPath, hostDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockSSHConfigResolver)(nil).Resolve), entry, sshConfigPath, hostDir)
}
