// Code generated by MockGen. DO NOT EDIT.
// Source: cmt/internal/config (interfaces: SSHCommandRunner,SSHConfigResolver)
//
// Generated by this command:
//
//	mockgen -destination=mock_ssh_interfaces.go -package=config cmt/internal/config SSHCommandRunner,SSHConfigResolver
//

// Package config is a generated GoMock package.
package config

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSHCommandRunner is a mock of SSHCommandRunner interface.
type MockSSHCommandRunner struct {
	ctrl     *gomock.Controller
	recorder *MockSSHCommandRunnerMockRecorder
	isgomock struct{}
}

// MockSSHCommandRunnerMockRecorder is the mock recorder for MockSSHCommandRunner.
type MockSSHCommandRunnerMockRecorder struct {
	mock *MockSSHCommandRunner
}

// NewMockSSHCommandRunner creates a new mock instance.
func NewMockSSHCommandRunner(ctrl *gomock.Controller) *MockSSHCommandRunner {
	mock := &MockSSHCommandRunner{ctrl: ctrl}
	mock.recorder = &MockSSHCommandRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHCommandRunner) EXPECT() *MockSSHCommandRunnerMockRecorder {
	return m.recorder
}

// Output mocks base method.
func (m *MockSSHCommandRunner) Output(args ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Output", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Output indicates an expected call of Output.
func (mr *MockSSHCommandRunnerMockRecorder) Output(args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Output", reflect.TypeOf((*MockSSHCommandRunner)(nil).Output), args...)
}

// MockSSHConfigResolver is a mock of SSHConfigResolver interface.
type MockSSHConfigResolver struct {
	ctrl     *gomock.Controller
	recorder *MockSSHConfigResolverMockRecorder
	isgomock struct{}
}

// MockSSHConfigResolverMockRecorder is the mock recorder for MockSSHConfigResolver.
type MockSSHConfigResolverMockRecorder struct {
	mock *MockSSHConfigResolver
}

// NewMockSSHConfigResolver creates a new mock instance.
func NewMockSSHConfigResolver(ctrl *gomock.Controller) *MockSSHConfigResolver {
	mock := &MockSSHConfigResolver{ctrl: ctrl}
	mock.recorder = &MockSSHConfigResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHConfigResolver) EXPECT() *MockSSHConfigResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockSSHConfigResolver) Resolve(entry *HostEntry, sshConfigPath, hostDir string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", entry, sshConfigPath, hostDir)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockSSHConfigResolverMockRecorder) Resolve(entry, sshConfigPath, hostDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockSSHConfigResolver)(nil).Resolve), entry, sshConfigPath, hostDir)
}
