---
- name: apt-get update
  become: True
  apt:
    
- name: Install prometheus
  become: True
  apt:
    name: prometheus

- name: mkdir /var/prometheus
  become: True
  file:
    path: /var/prometheus
    state: directory

- name: make compose.yml
  become: True
  template:
    src: compose.yml
    dest: /var/prometheus/compose.yml
  register: compose

- name: docker compose up
  shell:
    cmd: docker compose -f /var/prometheus/compose.yml up -d
    chdir: /var/prometheus
  when: compose.changed

- name: make prometheus.yml
  become: True
  template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
  notify: restart prometheus
