---
- name: Apt-get update
  become: true
  ansible.builtin.apt:

- name: Install prometheus
  become: true
  ansible.builtin.apt:
    name: prometheus

- name: Mkdir /var/prometheus
  become: true
  ansible.builtin.file:
    path: /var/prometheus
    state: directory
    mode: "0755"

- name: Make compose.yml
  become: true
  ansible.builtin.template:
    src: compose.yml
    dest: /var/prometheus/compose.yml
    mode: "0644"
  notify: Restart node-exporter

- name: Make prometheus.yml
  become: true
  ansible.builtin.template:
    src: prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    mode: "0644"
  notify:
    - Restart prometheus
    - Restart node-exporter
