---
- name: update apt
  become: true
  apt:

- name: Create directory for apt key
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download the Docker GPG key
  become: true
  get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc

- name: Set permissions for Docker's GPG key
  become: true
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to Apt sources
  become: true
  command: >
    echo "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: Update apt
  become: true
  apt:
    update_cache: yes
    
- name: Install Docker
  become: true
  apt:
    name:
    - docker-ce
    - docker-ce-cli 
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Start Docker
  become: true
  service:
    name: docker
    state: started
    enabled: yes

