---
- name: Include vars
  ansible.builtin.include_vars: "{{ ansible_facts['distribution'] }}.yml"
- name: Update apt
  become: true
  ansible.builtin.apt:

- name: Create directory for apt key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Check Docker GPG key
  become: true
  ansible.builtin.stat:
    path: /etc/apt/keyrings/docker.asc
  register: docker_gpg_key

- name: Download the Docker GPG key
  become: true
  ansible.builtin.get_url:
    url: "{{ docker_gpg_url }}"
    dest: /etc/apt/keyrings/docker.asc
    mode: "0644"
  when: not docker_gpg_key.stat.exists

- name: Set permissions for Docker's GPG key
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: "0644"

- name: Check architecture
  ansible.builtin.command:
    cmd: dpkg --print-architecture
  register: architecture
  changed_when: false

- name: Add Docker repository to Apt sources
  become: true
  ansible.builtin.template:
    src: docker.list
    dest: /etc/apt/sources.list.d/docker.list
    mode: "0644"
  notify: Install docker
