---
- name: include vars
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: update apt
  become: true
  apt:

- name: Create directory for apt key
  become: true
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Check Docker GPG key
  become: true
  stat:
    path: /etc/apt/keyrings/docker.asc
  register: docker_gpg_key

- name: Download the Docker GPG key
  become: true
  get_url:
    url: "{{ docker_gpg_url }}"
    dest: /etc/apt/keyrings/docker.asc
  when: docker_gpg_key.stat.exists == False

- name: Set permissions for Docker's GPG key
  become: true
  file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Check if Docker repository is already added
  stat:
    path: /etc/apt/sources.list.d/docker.list
  register: docker_repo

- name: Add Docker repository to Apt sources
  become: true
  shell: >
    echo "deb [arch=all signed-by=/etc/apt/keyrings/docker.asc] {{ docker_download_url }} {{ ansible_distribution_release }} stable"
    | tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: not docker_repo.stat.exists

- name: Update apt
  become: true
  apt:
    update_cache: yes
  when: not docker_repo.stat.exists
    
- name: Install Docker
  become: true
  apt:
    name:
    - docker-ce
    - docker-ce-cli 
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin
    state: present

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Enable Docker
  become: true
  service:
    name: docker
    enabled: yes

- name: Docker SDK for Python
  become: true
  apt:
    name: python3-docker
    state: present
