all:
  vars:
    ansible_user: ansible_user
    ansible_python_interpreter: /usr/bin/python3
  children:
    home_servers:
      children:
        home_ep:
          hosts:
            home-ep.ladon-tiaki.ts.net:
