name: Setup Compose CMT
description: Setup Go toolchain, SOPS decrypt, and SSH init for compose cmt jobs
runs:
  using: composite
  steps:
    - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6
      with:
        go-version-file: tools/compose/go.mod
        cache-dependency-path: tools/compose/go.sum
    - name: Authenticate to Google Cloud via Workload Identity Federation
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ env.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ env.SERVICE_ACCOUNT }}
        token_format: access_token
    - name: Install SOPS
      shell: bash
      run: |
        set -euo pipefail
        SOPS_VERSION="v3.9.4"
        curl -fsSL -o /tmp/sops "https://github.com/getsops/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux.amd64"
        chmod +x /tmp/sops
        sudo mv /tmp/sops /usr/local/bin/sops
        sops --version
    - name: Decrypt secrets with make sops-decrypt
      shell: bash
      run: |
        set -euo pipefail
        make sops-decrypt
    - name: Install cloudflared
      shell: bash
      run: |
        set -euo pipefail
        curl -fsSL \
          https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
          -o cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/local/bin/cloudflared
        cloudflared --version
