---
- name: apt-get update
  become: True
  apt:

- name: Install asterisk
  become: True
  apt: name='asterisk'
  notify: restart asterisk

- name: enable asterisk
  become: True
  service:
    name: asterisk
    enabled: yes
    state: started
  
- name: Make sip.conf
  become: True
  template:
    src: asterisk/sip.conf.j2
    dest: /etc/asterisk/sip.conf
  notify: restart asterisk

- name: Make cdr.conf
  become: True
  template:
    src: asterisk/cdr.conf.j2
    dest: /etc/asterisk/cdr.conf
  notify: restart asterisk

- name: Make cel.conf
  become: True
  template:
    src: asterisk/cel.conf.j2
    dest: /etc/asterisk/cel.conf
  notify: restart asterisk

- name: Make extensions.conf
  become: True
  template:
    src: asterisk/extensions.conf.j2
    dest: /etc/asterisk/extensions.conf
  notify: restart asterisk

- name: Make modules.conf
  become: True
  template:
    src: asterisk/modules.conf.j2
    dest: /etc/asterisk/modules.conf
  notify: restart asterisk
