- name: Swap off
  become: True
  command: swapoff -a

- name: Remove swap package
  become: True
  apt:
    name: dphys-swapfile
    state: absent

- name: Template /etc/fstab
  become: True
  template:
    src: raspberrypi/fstab.j2
    dest: /etc/fstab
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify: reboot

- name: Template init_task.service
  become: True
  template:
    src: raspberrypi/init_task.service
    dest: /etc/systemd/system/init_task.service
    owner: root
    group: root
    mode: 0644
    backup: yes

- name: Make init_task dir
  become: True
  file:
    path: /var/init_task
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Template startup.sh
  become: True
  template:
    src: raspberrypi/startup.sh
    dest: /var/init_task/startup.sh
    owner: root
    group: root
    mode: 0755
    backup: yes

- name: Template shutdown.sh
  become: True
  template:
    src: raspberrypi/shutdown.sh
    dest: /var/init_task/shutdown.sh
    owner: root
    group: root
    mode: 0755
    backup: yes

- name: Make log.old dir
  become: True
  file:
    path: /var/log.old
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Enable init_task service
  become: True
  systemd:
    name: init_task
    enabled: yes
    state: started
    daemon_reload: yes
