- name: Get swap state
  become: true
  ansible.builtin.command: swapon -v
  register: raspberrypi_swap_state
  check_mode: false
  changed_when: false

- name: Swap off
  become: true
  ansible.builtin.command: swapoff -a
  changed_when: true
  when: raspberrypi_swap_state.stdout != ''

- name: Remove swap package
  become: true
  ansible.builtin.apt:
    name: dphys-swapfile
    state: absent
