services:
  portainer:
    image: portainer/portainer-ce:2.27.0-rc2@sha256:00a51f306e154c0e1849d17d45bb4b2b947a2af28deb1e031db0adc076f97d26
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always
