services:
  portainer:
    image: portainer/portainer-ce:2.21.0-rc2
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    restart: always
