---
- name: Mkdir /var/home-assistant/config
  become: true
  ansible.builtin.file:
    path: /var/home-assistant/config
    state: directory
    mode: "0777"

- name: Make compose.yml
  ansible.builtin.template:
    src: compose.yml
    dest: /var/home-assistant/compose.yml
    mode: "0644"
  notify: restart home-assistant

- name: Make configuration.yaml
  ansible.builtin.template:
    src: configuration.yaml.j2
    dest: /var/home-assistant/config/configuration.yaml
    mode: "0644"
  notify: restart home-assistant
