name: PR CI
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened
permissions:
  pull-requests: read
jobs:
  pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: amannn/action-semantic-pull-request@48f256284bd46cdaab1048c3721360e808335d50 # v6.1.1
        with:
          requireScope: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  pr-body:
    name: PR body empty check
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - run: |
          if [[ "$PR_BODY" == "" ]]; then
            echo "PR body is empty"
            exit 1
          fi
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
